[project]
org-name = "wso2"
version = "0.8.32"
authors = ["WSO2"]
repository = "https://github.com/wso2-ballerina/module-twilio"
keywords = ["twilio", "sms", "call", "otp"]
license = ["Apache-2.0"]

[dependencies]
