[project]
license = "Apache-2.0"
org-name = "wso2"
version = "0.8.11"
authors = ["WSO2"]
repository = "https://github.com/wso2-ballerina/package-twilio"
keywords = ["ballerina", "twilio", "sms", "call", "otp"]