[package]
distribution = "2201.8.0"
org = "ballerinax"
name = "twilio"
version = "@toml.version@"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-twilio"
keywords = ["Communication/Call & SMS", "Cost/Paid"]
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
