[package]
distribution = "2201.2.1"
org = "ballerinax"
name = "twilio"
version = "3.1.0"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-twilio"
keywords = ["Communication/Call & SMS", "Cost/Paid"]
icon = "icon.png"
license = ["Apache-2.0"]
