[package]
distribution = "2201.0.0"
org = "ballerinax"
name = "twilio"
version = "2.2.1"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-twilio"
keywords = ["Communication/Call & SMS", "Cost/Paid"]
icon = "icon.png"
license = ["Apache-2.0"]
