[[dependency]]
org = "ballerina"
name = "url"
version = "1.1.0-beta.3"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "1.1.0-beta.3"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-beta.3"

[[dependency]]
org = "ballerina"
name = "auth"
version = "1.1.0-beta.3"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-beta.3"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-beta.3"

[[dependency]]
org = "ballerina"
name = "mime"
version = "1.1.0-beta.3"

[[dependency]]
org = "ballerina"
name = "os"
version = "1.1.0-beta.3"
