[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "twilio"
version = "5.0.1"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-twilio"
keywords = ["Communication/Call & SMS", "Cost/Paid", "Vendor/Twilio", "Area/Communication", "Type/Connector"]
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
