name: Pull Build

on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args: build ./twilio
      - name: Ballerina Tests
        # tests will be skipped if the PR is from a forked repository (as the secrets are not available)
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args: bal test --test-report --code-coverage --coverage-format=xml ./twilio
        env:
          REFRESH_URL: ${{ secrets.REFRESH_URL }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
